/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDeviceToHostImpl32 */

#ifndef _Included_jmtp_PortableDeviceToHostImpl32
#define _Included_jmtp_PortableDeviceToHostImpl32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDeviceToHostImpl32
 * Method:    copyFromPortableDeviceToHost
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljmtp/PortableDevice;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceToHostImpl32_copyFromPortableDeviceToHost
  (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
